contrib/libosmocore.spec.in: Depends on talloc 2.1.0
With recent commit (see below) libosmocore started using talloc API
talloc_pooled_object(), which is available only startinf from talloc
2.1.0.
Let's bump required version check accordingly.

Issue found by osmo-release.sh:
ERROR: configure.ac <talloc, 2.1.0> does NOT match contrib/*.spec.in <talloc, 2.0.1>!

Fixes: b72867f0e68c96ca25e1f9929ce92be0a802db6b
Change-Id: I6797e244118ce2ca7dd22050ff505d8442bba672