libosmocore.map: add missing symbols needed for osmo-qcdiag
Change 213fc420e broke osmo-qcdiag:

  /usr/bin/ld: diagchar_hdlc.o: in function `osmo_crc16_ccitt_byte':
  src/diagchar_hdlc.c:46: undefined reference to `osmo_crc16_ccitt_table'
  /usr/bin/ld: warning: creating DT_TEXTREL in a PIE
  collect2: error: ld returned 1 exit status
  make: *** [Makefile:8: osmo-qcdiag-log] Error 1

Change-Id: I7e84546b484db4822554681b31625d0520617d2b
Fixes: 213fc420e "Add libosmocore.map"